"""add shared_projects table

Revision ID: 79cacaeb07b8
Revises: 7cc619171d8e
Create Date: 2026-09-05 00:53:47.926405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79cacaeb07b8'
down_revision: Union[str, Sequence[str], None] = '7cc619171d8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_projects',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('share_token', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('manifest_json', sa.Text(), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=False),
    sa.Column('forked_from_id', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shared_projects_forked_from_id'), 'shared_projects', ['forked_from_id'], unique=False)
    op.create_index(op.f('ix_shared_projects_owner_id'), 'shared_projects', ['owner_id'], unique=False)
    op.create_index(op.f('ix_shared_projects_share_token'), 'shared_projects', ['share_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shared_projects_share_token'), table_name='shared_projects')
    op.drop_index(op.f('ix_shared_projects_owner_id'), table_name='shared_projects')
    op.drop_index(op.f('ix_shared_projects_forked_from_id'), table_name='shared_projects')
    op.drop_table('shared_projects')
    # ### end Alembic commands ###
