#include "trinity/firmware/CodeGen.hpp"

#include <cctype>
#include <sstream>

#include "trinity/core/Error.hpp"

namespace trinity::firmware {

namespace {

std::string upper(std::string value) {
    for (char& c : value) {
        c = static_cast<char>(std::toupper(static_cast<unsigned char>(c)));
    }
    return value;
}

std::string sanitize(const std::string& value) {
    std::string out;
    for (char c : value) {
        if (std::isalnum(static_cast<unsigned char>(c)) != 0) {
            out += static_cast<char>(std::toupper(static_cast<unsigned char>(c)));
        } else {
            out += '_';
        }
    }
    return out;
}

/// Trailing GPIO number ("GPIO2" -> 2, "PA5" -> 5, "GP18" -> 18).
/// Returns -1 when no trailing digits exist (never throws).
int pinNumber(const std::string& mcuPin) {
    size_t i = mcuPin.size();
    while (i > 0 && std::isdigit(static_cast<unsigned char>(mcuPin[i - 1])) != 0) {
        --i;
    }
    if (i == mcuPin.size()) {
        return -1;
    }
    try {
        return std::stoi(mcuPin.substr(i));
    } catch (...) {
        return -1;
    }
}

std::string familyMacro(const std::string& family) {
    return "TRINITY_FAMILY_" + sanitize(family);
}

void emitConfig(std::ostringstream& out, const FirmwareProject& project) {
    out << "// config.h — generated by Trinity FirmwareEngine. Do not edit by hand;\n";
    out << "// regenerate through the firmware engine so IR and sources stay in sync.\n";
    out << "// Project: " << project.name << " | MCU: " << project.mcu.model
        << " | Clock: " << project.clockHz << " Hz\n";
    out << "#pragma once\n\n";
    out << "#define TRINITY_MCU \"" << project.mcu.model << "\"\n";
    out << "#define " << familyMacro(project.mcu.family) << " 1\n";
    out << "#define TRINITY_CLOCK_HZ " << project.clockHz << "L\n\n";

    for (const auto& mapping : project.pinMappings) {
        const int number = pinNumber(mapping.mcuPin);
        out << "// " << mapping.mcuPin << ": " << mapping.function;
        if (!mapping.peripheral.empty()) {
            out << " on " << mapping.peripheral;
        }
        out << " (" << toString(mapping.direction) << ")\n";
        if (number >= 0) {
            out << "#define PIN_" << sanitize(mapping.mcuPin) << " " << number << "\n";
        } else {
            out << "// PIN_" << sanitize(mapping.mcuPin)
                << " has no numeric index; define manually if needed\n";
        }
    }
    if (!project.pinMappings.empty()) {
        out << "\n";
    }
    for (const auto& req : project.requirements) {
        const auto& params = req.params;
        switch (req.kind) {
            case RequirementKind::Uart:
                out << "// UART " << params.value("instance", "UART0") << ": TX="
                    << params.value("tx", "?") << " RX=" << params.value("rx", "?")
                    << " @ " << params.value("baud", 115200) << " baud\n";
                out << "#define " << sanitize(params.value("instance", "UART0"))
                    << "_BAUD " << params.value("baud", 115200) << "\n";
                break;
            case RequirementKind::I2c:
                out << "// I2C " << params.value("instance", "I2C0") << ": SDA="
                    << params.value("sda", "?") << " SCL=" << params.value("scl", "?")
                    << "\n";
                break;
            case RequirementKind::Pwm:
                out << "// PWM on " << params.value("pin", "?") << " @ "
                    << params.value("freq_hz", 1000) << " Hz\n";
                out << "#define PWM_FREQ_HZ " << params.value("freq_hz", 1000) << "\n";
                break;
            default:
                break;
        }
    }
}

void emitPlatform(std::ostringstream& out, const FirmwareProject& project) {
    out << "// platform.h — MCU abstraction selected by config.h.\n";
    out << "#pragma once\n\n";
    out << "#include \"config.h\"\n\n";
    out << "#if !defined(TRINITY_FAMILY_ESP32) && !defined(TRINITY_FAMILY_STM32F4) && \\\n"
           "    !defined(TRINITY_FAMILY_RP2040)\n";
    out << "#error \"Unsupported Trinity target: unknown MCU family\"\n";
    out << "#endif\n\n";
    out << "// Target: " << project.mcu.manufacturer << " " << project.mcu.model
        << " (" << project.mcu.architecture << ").\n";
    out << "// Toolchain: " << project.mcu.toolchain << "\n";
}

void emitSetup(std::ostringstream& out, const FirmwareProject& project) {
    out << "void setup() {\n";
    bool hasUart = false;
    int uartBaud = 115200;
    for (const auto& req : project.requirements) {
        if (req.kind == RequirementKind::Uart) {
            hasUart = true;
            uartBaud = req.params.value("baud", 115200);
            out << "  // UART " << req.params.value("instance", "UART0") << " on "
                << req.params.value("tx", "?") << "/" << req.params.value("rx", "?")
                << "\n";
            out << "  Serial.begin(" << uartBaud << ");\n";
        }
        if (req.kind == RequirementKind::I2c) {
            out << "  // I2C " << req.params.value("instance", "I2C0") << "\n";
            out << "  Wire.begin(PIN_" << sanitize(req.params.value("sda", "?"))
                << ", PIN_" << sanitize(req.params.value("scl", "?")) << ");\n";
        }
        if (req.kind == RequirementKind::Spi) {
            out << "  // SPI " << req.params.value("instance", "SPI0") << "\n";
            out << "  SPI.begin();\n";
        }
    }
    for (const auto& mapping : project.pinMappings) {
        if (mapping.direction == PinDirection::Output) {
            out << "  pinMode(PIN_" << sanitize(mapping.mcuPin) << ", OUTPUT);  // "
                << mapping.function << "\n";
        } else if (mapping.direction == PinDirection::Input) {
            const std::string mode =
                mapping.pull == "up" ? "INPUT_PULLUP" : "INPUT";
            out << "  pinMode(PIN_" << sanitize(mapping.mcuPin) << ", " << mode
                << ");  // " << mapping.function << "\n";
        }
    }
    for (const auto& req : project.requirements) {
        if (req.kind == RequirementKind::Pwm) {
            out << "  // PWM channel on " << req.params.value("pin", "?") << "\n";
            out << "#if defined(TRINITY_FAMILY_ESP32)\n";
            out << "  ledcSetup(0, PWM_FREQ_HZ, 8);\n";
            out << "  ledcAttachPin(PIN_" << sanitize(req.params.value("pin", "?"))
                << ", 0);\n";
            out << "#else\n";
            out << "  analogWriteResolution(8);\n";
            out << "#endif\n";
        }
    }
    if (!hasUart) {
        out << "  // No UART configured: status runs over the built-in LED blink.\n";
    }
    out << "}\n";
}

void emitLoop(std::ostringstream& out, const FirmwareProject& project) {
    out << "\nvoid loop() {\n";
    for (const auto& mapping : project.pinMappings) {
        if (mapping.direction == PinDirection::Output) {
            out << "  digitalWrite(PIN_" << sanitize(mapping.mcuPin)
                << ", HIGH);  // " << mapping.function << "\n";
        } else if (mapping.direction == PinDirection::Input) {
            out << "  (void)digitalRead(PIN_" << sanitize(mapping.mcuPin)
                << ");  // " << mapping.function << "\n";
        }
    }
    for (const auto& req : project.requirements) {
        if (req.kind == RequirementKind::Uart) {
            out << "  if (Serial.available()) {\n";
            out << "    Serial.write(Serial.read());  // echo\n";
            out << "  }\n";
        }
        if (req.kind == RequirementKind::Pwm) {
            out << "  for (int duty = 0; duty < 255; duty += 5) {\n";
            out << "#if defined(TRINITY_FAMILY_ESP32)\n";
            out << "    ledcWrite(0, duty);\n";
            out << "#else\n";
            out << "    analogWrite(PIN_" << sanitize(req.params.value("pin", "?"))
                << ", duty);\n";
            out << "#endif\n";
            out << "    delay(10);\n";
            out << "  }\n";
        }
    }
    out << "  delay(100);\n";
    out << "}\n";
}

}  // namespace

std::vector<SourceFile> generateSources(const FirmwareProject& project) {
    if (!project.hasMcu || project.mcu.model.empty()) {
        throw core::RequestValidationError("Cannot generate sources without an MCU",
                                           {{"project", project.name}}, "engines");
    }
    std::ostringstream config;
    emitConfig(config, project);
    std::ostringstream platform;
    emitPlatform(platform, project);

    std::ostringstream main;
    main << "// main.cpp — generated by Trinity FirmwareEngine for " << project.name
         << " (" << project.mcu.model << ").\n";
    main << "// Arduino framework: setup() runs once, loop() repeats.\n";
    main << "#include <Arduino.h>\n";
    bool needsWire = false;
    bool needsSpi = false;
    for (const auto& req : project.requirements) {
        if (req.kind == RequirementKind::I2c) {
            needsWire = true;
        }
        if (req.kind == RequirementKind::Spi) {
            needsSpi = true;
        }
    }
    if (needsWire) {
        main << "#include <Wire.h>\n";
    }
    if (needsSpi) {
        main << "#include <SPI.h>\n";
    }
    main << "#include \"config.h\"\n";
    main << "#include \"platform.h\"\n\n";
    std::ostringstream body;
    emitSetup(body, project);
    emitLoop(body, project);
    main << body.str();

    return {{"main.cpp", main.str()},
            {"config.h", config.str()},
            {"platform.h", platform.str()}};
}

}  // namespace trinity::firmware
