#include "trinity/intelligence/Planner.hpp"

#include "trinity/core/Logger.hpp"
#include "trinity/core/Uuid.hpp"
#include "trinity/engines/EngineRegistry.hpp"
#include "trinity/workflows/Executor.hpp"
#include "trinity/workflows/Workflow.hpp"

namespace trinity::intelligence {

core::Json PlanStepResult::toJson() const {
    return core::Json{{"tool_call", toolCall.toJson()},
                      {"job_id", jobId},
                      {"executed", executed},
                      {"skipped", skipped},
                      {"success", success},
                      {"response", response}};
}

PlanStepResult PlanStepResult::fromJson(const core::Json& json) {
    PlanStepResult step;
    if (json.contains("tool_call")) {
        step.toolCall = ToolCall::fromJson(json["tool_call"]);
    }
    step.jobId = json.value("job_id", "");
    step.executed = json.value("executed", false);
    step.skipped = json.value("skipped", false);
    step.success = json.value("success", false);
    step.response = json.value("response", core::Json::object());
    return step;
}

core::Json PlanResult::toJson() const {
    core::Json stepsJson = core::Json::array();
    for (const auto& step : steps) {
        stepsJson.push_back(step.toJson());
    }
    return core::Json{
        {"success", success}, {"request_id", requestId}, {"workflow_id", workflowId}, {"steps", stepsJson}, {"error", error}};
}

PlanResult PlanResult::fromJson(const core::Json& json) {
    PlanResult result;
    result.success = json.value("success", false);
    result.requestId = json.value("request_id", "");
    result.workflowId = json.value("workflow_id", "");
    result.error = json.value("error", core::Json(nullptr));
    if (json.contains("steps") && json["steps"].is_array()) {
        for (const auto& item : json["steps"]) {
            result.steps.push_back(PlanStepResult::fromJson(item));
        }
    }
    return result;
}

Planner::Planner(IModelProvider& model, workflows::WorkflowExecutor& executor,
                 engines::EngineRegistry& registry)
    : model_(&model), executor_(&executor), registry_(&registry) {}

PlanResult Planner::planAndExecute(const ModelRequest& request) {
    auto& log = core::Logger::instance();
    PlanResult plan;
    plan.requestId = request.requestId;

    const auto planResultResult = model_->generatePlan(request);
    if (!planResultResult.isOk()) {
        plan.success = false;
        plan.error = planResultResult.error().toJson();
        log.info("planner", "plan generation failed",
                 core::Json{{"request_id", request.requestId}});
        return plan;
    }

    const ModelResponse response = planResultResult.value();
    if (!response.success) {
        // Model refusal: execute nothing.
        plan.success = false;
        plan.error = response.error;
        log.info("planner", "plan refused; executed nothing",
                 core::Json{{"request_id", request.requestId}});
        return plan;
    }

    std::vector<ToolCall> calls = response.toolCalls;
    if (calls.empty() && response.hasToolCall) {
        calls.push_back(response.toolCall);
    }
    
    return executeToolCalls(calls, request.requestId);
}

PlanResult Planner::executeToolCalls(const std::vector<ToolCall>& calls, const std::string& requestId) {
    auto& log = core::Logger::instance();
    PlanResult plan;
    plan.requestId = requestId;
    plan.success = false;

    if (calls.empty()) {
        plan.success = true;
        log.info("planner", "plan complete; no tool calls",
                 core::Json{{"request_id", requestId}});
        return plan;
    }

    // Construct a workflow from the tool calls
    workflows::Workflow workflow;
    workflow.workflowId = "wf-" + core::newUuid();
    workflow.name = "LLM Plan Workflow";
    workflow.description = "Generated by LLM Planner";
    workflow.metadata = core::Json{{"request_id", requestId}};

    std::vector<std::string> nodeIds;
    
    // Add nodes
    for (size_t i = 0; i < calls.size(); ++i) {
        workflows::WorkflowNode node;
        node.id = "N" + std::to_string(i);
        node.engine = calls[i].engine;
        node.operation = calls[i].operation;
        node.input = calls[i].parameters;
        
        // Convert any special "{{...}}" references into inputFrom
        // This is a simplified extraction; a real LLM might emit them directly.
        // We'll trust the LLM to emit inputFrom in the ToolCall if we add it to the schema,
        // but for now, we'll assume linear dependency for demonstration unless specified.
        if (calls[i].parameters.contains("_inputFrom") && calls[i].parameters["_inputFrom"].is_object()) {
            node.inputFrom = calls[i].parameters["_inputFrom"];
            // Erase the internal property
            node.input.erase("_inputFrom");
        }

        workflow.nodes.push_back(std::move(node));
        nodeIds.push_back("N" + std::to_string(i));
    }

    // Add edges (linear workflow by default if not specified)
    for (size_t i = 1; i < nodeIds.size(); ++i) {
        workflows::WorkflowEdge edge;
        edge.edgeId = "E" + std::to_string(i);
        edge.fromNode = nodeIds[i - 1];
        edge.toNode = nodeIds[i];
        edge.type = workflows::EdgeType::DependsOn;
        workflow.edges.push_back(std::move(edge));
    }

    // Execute workflow
    try {
        workflows::WorkflowResult wfResult = executor_->runInline(workflow);
        plan.success = wfResult.success;
        plan.workflowId = workflow.workflowId;
        plan.error = wfResult.error;
        
        // Map back to steps
        for (size_t i = 0; i < calls.size(); ++i) {
            PlanStepResult step;
            step.toolCall = calls[i];
            
            auto nodeIt = std::find_if(wfResult.workflow.nodes.begin(), wfResult.workflow.nodes.end(), 
                                       [&](const workflows::WorkflowNode& n) { return n.id == nodeIds[i]; });
            if (nodeIt != wfResult.workflow.nodes.end()) {
                if (nodeIt->status == workflows::NodeStatus::Completed) {
                    step.executed = true;
                    step.success = true;
                    step.jobId = "wf-" + nodeIt->id;
                    step.response = core::Json{
                        {"success", true},
                        {"job_id", step.jobId},
                        {"result", wfResult.nodeResults[nodeIt->id]}
                    };
                } else if (nodeIt->status == workflows::NodeStatus::Failed) {
                    step.executed = true;
                    step.success = false;
                    step.jobId = "wf-" + nodeIt->id;
                    step.response = core::Json{
                        {"success", false},
                        {"job_id", step.jobId},
                        {"errors", core::Json::array({nodeIt->error})}
                    };
                } else if (nodeIt->status == workflows::NodeStatus::Skipped || nodeIt->status == workflows::NodeStatus::Queued) {
                    step.skipped = true;
                    step.executed = false;
                    step.success = false;
                }
            }
            plan.steps.push_back(std::move(step));
        }
        
    } catch (const std::exception& exc) {
        plan.success = false;
        plan.error = core::makeError(core::ErrorCode::EngineExecutionError, exc.what(), "planner").toJson();
    }

    log.info("planner", "plan finished",
             core::Json{{"request_id", requestId},
                        {"success", plan.success},
                        {"workflow_id", plan.workflowId},
                        {"steps", plan.steps.size()}});
    return plan;
}

}  // namespace trinity::intelligence
