"""Deterministic, free-toolchain firmware project generator."""
from __future__ import annotations

import json
import re
from dataclasses import dataclass
from typing import Iterable

from app.firmware.models import FirmwareSpec, FirmwareTarget, PeripheralSpec


@dataclass(frozen=True)
class GeneratedFirmwareProject:
    files: dict[str, str]
    assumptions: list[str]


def _identifier(value: str) -> str:
    return re.sub(r"[^a-zA-Z0-9_]", "_", value).strip("_").lower() or "trinity_firmware"


def _c_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


class FirmwareGenerator:
    def generate(self, target: FirmwareTarget, spec: FirmwareSpec) -> GeneratedFirmwareProject:
        name = _identifier(spec.project_name)
        files: dict[str, str] = {
            "README.md": self._readme(target, spec),
            "firmware_spec.json": json.dumps(spec.model_dump(mode="json"), indent=2),
            "TARGET.md": self._target_notes(target),
        }
        if target.framework == "ESP-IDF":
            files.update(self._esp_idf(name, target, spec))
        elif target.framework == "Arduino AVR":
            files.update(self._platformio(name, target, spec, "arduino", "uno"))
        elif target.framework == "STM32 HAL":
            files.update(self._stm32(name, target, spec))
        elif target.framework == "Pico SDK":
            files.update(self._pico(name, target, spec))
        elif target.framework == "Zephyr":
            files.update(self._zephyr(name, target, spec))
        elif target.framework == "PX4":
            files.update(self._px4(name, target, spec))
        elif target.framework == "ArduPilot":
            files.update(self._ardupilot(name, target, spec))
        elif target.framework in {"Betaflight", "INAV"}:
            files.update(self._flight_controller_extension(name, target, spec))
        else:
            raise ValueError(f"No generator is registered for framework {target.framework!r}")
        if spec.include_tests:
            files["tests/test_spec.py"] = self._spec_test(target, spec)
        return GeneratedFirmwareProject(files=files, assumptions=self._assumptions(target, spec))

    def _readme(self, target: FirmwareTarget, spec: FirmwareSpec) -> str:
        safety = "Flight code must be tested in SITL, then on a restrained bench with propellers removed before any flight." if target.kind.value == "flight_controller" else "Test on a current-limited bench supply before connecting external loads."
        return f"""# {spec.project_name}\n\nGenerated by Trinity Firmware Engine for **{target.name}** ({target.framework}).\n\n## Precision contract\n\nThis project was generated from `firmware_spec.json`. The target, framework, pins, peripherals, and requested features are explicit and should be reviewed before flashing.\n\n## Build\n\n```text\n{target.build_command}\n```\n\n## Flash\n\n```text\n{target.flash_command}\n```\n\n## Safety\n\n{safety}\nThe generated code is a deterministic reference project, not a certification of hardware correctness. Confirm the exact board revision, voltage levels, pin multiplexing, clock tree, boot configuration, and peripheral datasheets.\n"""

    def _target_notes(self, target: FirmwareTarget) -> str:
        peripherals = ", ".join(target.supported_peripherals)
        notes = "\n".join(f"- {note}" for note in target.notes)
        return f"# Target profile\n\n- **Board:** {target.board}\n- **MCU:** {target.mcu}\n- **Framework:** {target.framework}\n- **Language:** {target.language}\n- **Build system:** {target.build_system}\n- **Peripherals:** {peripherals}\n\n## Profile notes\n\n{notes}\n"

    def _common_c_source(self, target: FirmwareTarget, spec: FirmwareSpec, includes: str, setup: str, loop: str) -> str:
        pins = "\n".join(f"// Pin {pin.name}: {pin.pin} ({pin.function})" for pin in spec.pins) or "// No explicit pin assignments supplied."
        features = ", ".join(spec.features) or "heartbeat"
        return f"""/* Generated by Trinity Firmware Engine. Review before flashing. */\n#include <stdint.h>\n#include <stdbool.h>\n{includes}\n\n/* Target: {target.board} / {target.mcu} */\n/* Requested features: {_c_string(features)} */\n{pins}\n\nstatic volatile bool trinity_safe_mode = {str(spec.safety_mode == 'flight').lower()};\n\nstatic void trinity_init(void) {{\n{setup}\n}}\n\nstatic void trinity_loop(void) {{\n{loop}\n}}\n\nint main(void) {{\n    trinity_init();\n    for (;;) {{\n        trinity_loop();\n    }}\n    return 0;\n}}\n"""

    def _esp_idf(self, name: str, target: FirmwareTarget, spec: FirmwareSpec) -> dict[str, str]:
        source = self._common_c_source(target, spec, "#include \"freertos/FreeRTOS.h\"\n#include \"freertos/task.h\"\n#include \"driver/gpio.h\"", "    /* Configure only pins declared in firmware_spec.json. */", "    /* Add application tasks here; flight-safe mode never arms hardware automatically. */\n    vTaskDelay(pdMS_TO_TICKS(1000));")
        return {
            "CMakeLists.txt": f"cmake_minimum_required(VERSION 3.16)\ninclude($ENV{{IDF_PATH}}/tools/cmake/project.cmake)\nproject({name})\n",
            "main/CMakeLists.txt": "idf_component_register(SRCS \"main.c\" INCLUDE_DIRS \".\")\n",
            "main/main.c": source,
            "sdkconfig.defaults": "CONFIG_COMPILER_OPTIMIZATION_SIZE=y\n",
        }

    def _platformio(self, name: str, target: FirmwareTarget, spec: FirmwareSpec, platform: str, board: str) -> dict[str, str]:
        source = self._cpp_source(target, spec)
        return {
            "platformio.ini": f"[env:{board}]\nplatform = atmelavr\nframework = {platform}\nboard = {board}\nmonitor_speed = 115200\n",
            "src/main.cpp": source,
        }

    def _stm32(self, name: str, target: FirmwareTarget, spec: FirmwareSpec) -> dict[str, str]:
        source = self._common_c_source(target, spec, "#include \"main.h\"", "    HAL_Init();\n    /* Add CubeMX-generated clock/GPIO/peripheral initialization here. */", "    HAL_Delay(1000);")
        return {
            "CMakeLists.txt": f"cmake_minimum_required(VERSION 3.22)\nproject({name} C)\nadd_executable({name} src/main.c)\n",
            "src/main.c": source,
            "include/main.h": "#pragma once\n#include <stdint.h>\nvoid Error_Handler(void);\n",
            "toolchain.cmake": "# Configure arm-none-eabi-gcc and the exact STM32F411 device flags here.\n",
        }

    def _pico(self, name: str, target: FirmwareTarget, spec: FirmwareSpec) -> dict[str, str]:
        source = self._common_c_source(target, spec, "#include \"pico/stdlib.h\"", "    stdio_init_all();", "    sleep_ms(1000);")
        return {
            "CMakeLists.txt": f"cmake_minimum_required(VERSION 3.13)\ninclude($ENV{{PICO_SDK_PATH}}/external/pico_sdk_import.cmake)\nproject({name} C CXX ASM)\npico_sdk_init()\nadd_executable({name} src/main.c)\ntarget_link_libraries({name} pico_stdlib)\npico_add_extra_outputs({name})\n",
            "src/main.c": source,
        }

    def _zephyr(self, name: str, target: FirmwareTarget, spec: FirmwareSpec) -> dict[str, str]:
        source = """#include <zephyr/kernel.h>\n#include <zephyr/device.h>\n\nint main(void)\n{\n    while (1) {\n        /* Bind peripherals through devicetree overlays, not guessed pins. */\n        k_msleep(1000);\n    }\n    return 0;\n}\n"""
        return {
            "CMakeLists.txt": "find_package(Zephyr REQUIRED HINTS $ENV{ZEPHYR_BASE})\nproject(trinity_firmware)\ntarget_sources(app PRIVATE src/main.c)\n",
            "prj.conf": "CONFIG_SERIAL=y\nCONFIG_GPIO=y\n",
            "src/main.c": source,
        }

    def _cpp_source(self, target: FirmwareTarget, spec: FirmwareSpec) -> str:
        return f"""#include <Arduino.h>\n\n// Target: {target.board} / {target.mcu}\n// Safety mode: {spec.safety_mode}\n\nvoid setup() {{\n  Serial.begin(115200);\n  // Configure only the explicit pin map from firmware_spec.json.\n}}\n\nvoid loop() {{\n  // Requested features: {_c_string(', '.join(spec.features) or 'heartbeat')}\n  delay(1000);\n}}\n"""

    def _px4(self, name: str, target: FirmwareTarget, spec: FirmwareSpec) -> dict[str, str]:
        return {
            "src/trinity_module.cpp": f"""#include <px4_platform_common/module.h>\n#include <px4_platform_common/log.h>\n\nextern \"C\" __EXPORT int trinity_module_main(int argc, char *argv[])\n{{\n    PX4_INFO(\"Trinity module started for {target.board}\");\n    // Integrate through PX4 uORB and parameter APIs; do not directly arm or drive actuators.\n    return 0;\n}}\n""",
            "src/CMakeLists.txt": "px4_add_module(MODULE modules__trinity SRCS trinity_module.cpp)\n",
        }

    def _ardupilot(self, name: str, target: FirmwareTarget, spec: FirmwareSpec) -> dict[str, str]:
        return {
            "libraries/AP_Trinity/AP_Trinity.h": "#pragma once\nclass AP_Trinity { public: void update(); };\n",
            "libraries/AP_Trinity/AP_Trinity.cpp": f"""#include \"AP_Trinity.h\"\n\nvoid AP_Trinity::update()\n{{\n    // Integrate through ArduPilot scheduler, parameters, and HAL APIs.\n    // Do not bypass EKF, arming checks, failsafes, or actuator safety interlocks.\n}}\n""",
            "libraries/AP_Trinity/library.properties": "name=AP_Trinity\nversion=0.1.0\n",
        }

    def _flight_controller_extension(self, name: str, target: FirmwareTarget, spec: FirmwareSpec) -> dict[str, str]:
        return {
            "src/trinity_feature.c": f"""/* {target.framework} extension skeleton for {target.board}. */\n#include <stdint.h>\n\nvoid trinity_feature_init(void)\n{{\n    /* Bind the real target's pin/peripheral definitions before flashing. */\n}}\n\nvoid trinity_feature_update(void)\n{{\n    /* Preserve the flight stack's scheduler, failsafes, and arming checks. */\n}}\n""",
            "README_EXTENSION.md": f"# {target.framework} extension\n\nThis project is an extension point, not a replacement flight-controller firmware image. Select the exact {target.framework} target definition and run its native build/test process before hardware flashing.\n",
        }

    def _spec_test(self, target: FirmwareTarget, spec: FirmwareSpec) -> str:
        return f"""import json\nfrom pathlib import Path\n\n\ndef test_generated_spec_is_explicit():\n    spec = json.loads(Path(__file__).parents[1].joinpath('firmware_spec.json').read_text())\n    assert spec['target_id'] == {target.id!r}\n    assert spec['safety_mode'] in {{'development', 'bench', 'flight'}}\n"""

    def _assumptions(self, target: FirmwareTarget, spec: FirmwareSpec) -> list[str]:
        assumptions = [
            f"Generation is pinned to the registered target profile {target.id}; unsupported boards are rejected.",
            "Pin multiplexing and peripheral electrical characteristics must be confirmed against the exact board revision.",
            "The generated project uses free/open-source toolchains but does not install proprietary vendor SDKs automatically.",
        ]
        if target.kind.value == "flight_controller":
            assumptions.append("Flight-controller output is an extension/module scaffold and does not replace the vendor flight stack or safety interlocks.")
        if not spec.pins:
            assumptions.append("No explicit pin assignments were supplied; generated code does not guess hardware pins.")
        return assumptions
